server:
  port: 1002
spring:
  application:
    name: IDEAL-GATEWAY
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: springlearn
          # eureka 模块注册中心貌似有问题，无法通过模块路由
#          uri: lb://IDEAL-SPRINGLEARN
          uri: http://127.0.0.1:1015
          predicates:
            - Path=/ysl/gateway/**
          filters:
            - StripPrefix=2


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    register-with-eureka: true
    fetch-registry: true